In [2]:
import numpy as np
a = np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [3]:
b = np.arange(2,40,4)
b

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38])

In [13]:
c = np.arange(2,20,2)
c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
c = c.reshape((3,3))
c

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [18]:
d = np.arange(1,100,2)

d = d.reshape(10,5)
d

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [19]:
b = b.flatten() # inverse of reshape. convert array to list 
b

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38])

In [21]:
d = d.flatten()
d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [22]:
a.ravel()
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

| Feature                    | `flatten()`                                                | `ravel()`                                          |
| -------------------------- | ---------------------------------------------------------- | -------------------------------------------------- |
| **Copy or View**           | Always returns a **copy**                                  | Returns a **view** (if possible), otherwise a copy |
| **Memory Usage**           | Uses **more memory** (due to copy)                         | **More efficient** (less memory if view)           |
| **Original Array Changes** | No effect on original array if you modify flattened output | If view, changes can affect original array         |
| **Syntax**                 | `array.flatten()`                                          | `np.ravel(array)` or `array.ravel()`               |
