In [1]:
import numpy as np
np.empty((3,3),dtype= float)

array([[ 6.17779239e-31, -1.23555848e-30,  3.08889620e-31],
       [-1.23555848e-30,  2.68733969e-30, -8.34001973e-31],
       [ 3.08889620e-31, -8.34001973e-31,  4.78778910e-31]])

In [2]:
np.ones(4)

array([1., 1., 1., 1.])

In [4]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.ones((3,5),dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2,3), dtype= str)

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [8]:
np.zeros((2,3), dtype= str)

array([['', '', ''],
       ['', '', '']], dtype='<U1')

In [9]:
np.ones((2,3), dtype= bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [10]:
np.zeros((2,3), dtype= bool)

array([[False, False, False],
       [False, False, False]])