In [1]:
import numpy as np
lst = [1,2,2,3,4,4,5]

print('1D array')
a = np.array([lst])
a

1D array


array([[1, 2, 2, 3, 4, 4, 5]])

In [5]:
print('2D array')
b = np.array([[1,2,3,4,5,6,9], 
             [23,34,5,53,52,34,8]])
b

2D array


array([[ 1,  2,  3,  4,  5,  6,  9],
       [23, 34,  5, 53, 52, 34,  8]])

In [6]:
type(a)

numpy.ndarray

In [7]:
print(a.size)
print(b.size)

7
14


In [8]:
print('3D Array')
c = np.array([[[12,3,4,5,5],[23,4,5,6,7],[21,3,45,67,9]]])
c

3D Array


array([[[12,  3,  4,  5,  5],
        [23,  4,  5,  6,  7],
        [21,  3, 45, 67,  9]]])

In [9]:
print(c.shape)

(1, 3, 5)


In [10]:
print(c.dtype)

int64


In [19]:
d = np.array([[2.4,4,5.8,9,12],[2,45.7,2,8,9],[1,2.9,3,49,2.8]])
print(d.dtype)

float64


In [20]:
print(d.transpose)
d

<built-in method transpose of numpy.ndarray object at 0x11676f9f0>


array([[ 2.4,  4. ,  5.8,  9. , 12. ],
       [ 2. , 45.7,  2. ,  8. ,  9. ],
       [ 1. ,  2.9,  3. , 49. ,  2.8]])

In [21]:
c.transpose
c

array([[[12,  3,  4,  5,  5],
        [23,  4,  5,  6,  7],
        [21,  3, 45, 67,  9]]])

In [22]:
print(c.T) 

[[[12]
  [23]
  [21]]

 [[ 3]
  [ 4]
  [ 3]]

 [[ 4]
  [ 5]
  [45]]

 [[ 5]
  [ 6]
  [67]]

 [[ 5]
  [ 7]
  [ 9]]]
