In [1]:
import numpy as np
np.random.random(2)

array([0.60829427, 0.36932655])

In [2]:
np.random.random((2,2))

array([[0.76278148, 0.60418118],
       [0.09155863, 0.7976827 ]])

In [3]:
np.random.randint(1,10)

9

In [4]:
np.random.randint(1,10,(2,2))

array([[1, 7],
       [2, 4]])

In [8]:
np.random.randint(1,10,(3,4,5))

array([[[4, 5, 4, 1, 7],
        [4, 7, 8, 9, 2],
        [1, 4, 6, 2, 4],
        [7, 6, 3, 5, 4]],

       [[7, 4, 4, 2, 4],
        [5, 8, 7, 5, 8],
        [1, 5, 1, 1, 9],
        [2, 6, 9, 8, 8]],

       [[1, 6, 8, 2, 3],
        [9, 7, 8, 3, 8],
        [1, 4, 5, 3, 8],
        [2, 7, 2, 4, 7]]])

In [9]:
np.random.rand(2,2)

array([[0.42627794, 0.6876425 ],
       [0.43691109, 0.26654527]])

In [13]:
np.random.randn(2,2)

array([[ 0.5960552 , -0.90737406],
       [ 0.33620234, -0.02128521]])

In [16]:
a = np.arange(1,10)
np.random.choice(a)

np.int64(8)