In [17]:
import numpy as np 
a = np.arange(1,51)
a= a.reshape(10,5)
a


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [20]:
a[0]


array([1, 2, 3, 4, 5])

In [21]:
a[1,0] #2nd array 1st value

6

In [22]:
a[3,4]

20

In [23]:
a[2:5] # starting to ending index

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
a[:,3] # all rows of 4th column

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49])

In [25]:
a[2:5,4] # print 5th column's 2,3,4th rows value

array([15, 20, 25])

In [26]:
a[:,:] # all rows and all column

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [27]:
a[:, 2:5] #all the rows to the 3rd column to 5th column


array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [28]:
a[:, 2:5].dtype

dtype('int64')